export default [
    {
        id:1,
        postedOn : '2023-10-28',
        title: 'iOS Developer',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["SwiftUI", "UiKit", "Core Data"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 2,
        postedOn: '2023-10-24',
        title: "Frontend Developer",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["Javascript", "Nextjs", "Tailwind CSS"],
        job_link: "https://www.amazon.jobs/en/",
      },
      {
        id: 3,
        postedOn: '2023-11-02',
        title: "Android Developer",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Facebook",
        skills: ["Kotlin", "MVVM"],
        job_link: "https://facebook.com/careers",
      },
      {
        id: 4,
        postedOn: '2023-11-01',
        title: "Developer Advocate",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Netflix",
        companyUrl: "https://facebook.com",
        skills: ["web3", "Content Creation", "Community"],
        job_link: "https://jobs.netflix.com/",
      },
      {
        id: 5,
        postedOn: '2023-11-05',
        title: 'Backend Developer',
        company: 'Google',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ['Node.js', 'Express', 'MongoDB'],
        job_link: 'https://careers.google.com/jobs/',
      },
      {
        id: 6,
        postedOn: '2023-10-31',
        title: 'Data Scientist',
        company: 'Microsoft',
        type: 'Full Time',
        experience: 'Senior Level',
        location: 'In-office',
        skills: ['Python', 'TensorFlow', 'Data Mining'],
        job_link: 'https://careers.microsoft.com/',
      },
      {
        id: 7,
        postedOn: '2023-11-03',
        title: 'Developer Advocate',
        company: 'Tesla',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ['AWS', 'Docker', 'Kubernetes'],
        job_link: 'https://www.tesla.com/careers',
      },
      {
        id: 8,
        postedOn: '2023-10-30',
        title: 'UX/UI Designer',
        company: 'Spotify',
        type: 'Contract',
        experience: 'Junior Level',
        location: 'Hybrid',
        skills: ['Figma', 'Sketch', 'User Research'],
        job_link: 'https://www.spotifyjobs.com/',
      },
      {
        id: 9,
        postedOn: '2023-11-06',
        title: 'Blockchain Engineer',
        company: 'Coinbase',
        type: 'Full Time',
        experience: 'Senior Level',
        location: 'Remote',
        skills: ['Solidity', 'Ethereum', 'Smart Contracts'],
        job_link: 'https://www.coinbase.com/careers',
      },
      {
        id: 10,
        postedOn: '2023-11-07',
        title: 'Cloud Architect',
        company: 'Oracle',
        type: 'Part Time',
        experience: 'Mid Level',
        location: 'In-office',
        skills: ['AWS', 'Azure', 'Cloud Security'],
        job_link: 'https://www.oracle.com/careers/',
      },
      
]